cabal-version:      3.0
name:               hat
version:            0.1.0
synopsis:           A terminal multiplexer
license:            ISC
author:             Bryan Richter
maintainer:         b@chreekat.net
build-type:         Simple

common defaults
    default-language:   GHC2021
    default-extensions:
        DerivingStrategies
        DuplicateRecordFields
        LambdaCase
        NoFieldSelectors
        OverloadedRecordDot
        OverloadedStrings
    ghc-options:        -Wall -Wcompat -Wincomplete-record-updates
                        -Wincomplete-uni-patterns -Wredundant-constraints

library
    import:             defaults
    hs-source-dirs:     src
    exposed-modules:
        Hat.Client
        Hat.Client.Draw
        Hat.Command.Parser
        Hat.Client.Tty
        Hat.Geometry
        Hat.Log
        Hat.Model
        Hat.Model.Ids
        Hat.Model.Options
        Hat.Pty
        Hat.Server
        Hat.Server.Format
        Hat.Server.Keys
        Hat.Server.Layout
        Hat.Server.Render
        Hat.Socket
        Hat.Term.Cell
        Hat.Term.Emulator
        Hat.Wire
    include-dirs:       cbits
    c-sources:          cbits/hat_shim.c
    pkgconfig-depends:  vterm
    build-depends:
        aeson,
        async,
        base,
        bytestring,
        containers,
        directory,
        filepath,
        megaparsec,
        network,
        process,
        serialise,
        stm,
        text,
        time,
        unix,
        vector

executable hat
    import:             defaults
    hs-source-dirs:     app
    main-is:            Main.hs
    ghc-options:        -threaded -rtsopts "-with-rtsopts=-N2"
    build-depends:
        base,
        directory,
        hat,
        network,
        text,
        unix

executable gen-fixtures
    import:             defaults
    hs-source-dirs:     tools
    main-is:            GenFixtures.hs
    ghc-options:        -threaded
    build-depends:
        base,
        bytestring,
        hat,
        vector,
        text

test-suite hat-test
    import:             defaults
    type:               exitcode-stdio-1.0
    hs-source-dirs:     test
    main-is:            Main.hs
    build-tool-depends: hat:hat
    other-modules:
        Hat.Command.ParserSpec
        Hat.IntegrationSpec
        Hat.PtySpec
        Hat.SocketSpec
        Hat.Server.FormatSpec
        Hat.Server.KeysSpec
        Hat.Server.LayoutSpec
        Hat.Server.RenderSpec
        Hat.Term.EmulatorSpec
        Hat.Term.GoldenSpec
        Hat.WireSpec
    ghc-options:        -threaded
    build-depends:
        base,
        bytestring,
        containers,
        hspec,
        process,
        QuickCheck,
        hat,
        vector,
        text,
        unix
